### ISSUE TITLE
Gravestones

### ISSUE THREAD

**Issue by J-Sit89** [BeansGalaxy/BeansBackpacks#7] opened 2023-12-24 00:27 UTC
Hey there!  it seems like when u die with the backpack on and have a gravestone mod equiped, the backpack deletes all the items inside.  any way to fix that?

**Comment by BeansGalaxy** [comment] 2023-12-26 01:10
Who makes the gravestone mod you're using?

**Comment by J-Sit89** [comment] 2023-12-26 01:26
Patbox

**Comment by BeansGalaxy** [comment] 2023-12-28 05:29
The issue is that mod stops the line of code that my code looks for to tell if the player dies. I'm about a week away from releasing v2.0 so my focus is on that, but it will be fixed in that version. 
(Also it's a cool looking grave mod. I always thought the cobblestone gravestone looked kinda corny)

**Comment by BeansGalaxy** [comment] 2024-03-08 20:56
Compat is working in latest version, Idk if this issue was for V1 or V2 but it's solved nonetheless

**Closed as completed by BeansGalaxy** 2024-03-08 20:56 UTC
Labels: compatibility
